language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: status_querier
  on:
    tags: true
    repo: westfieldlabs/status_querier